version: 2
updates:
- package-ecosystem: gomod
  directory: '/'
  schedule:
    interval: 'weekly'
  labels:
  - 'dependencies'
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.15.2
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.8.0
    - 1.8.1
- package-ecosystem: 'npm'
  directory: '/'
  schedule:
    interval: 'weekly'
  labels:
  - 'dependencies'
  versioning-strategy: increase
