run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - unused
    - gosimple
    - govet
    - staticcheck
    - ineffassign
    - stylecheck
    - unconvert
    - goconst
    - misspell
    - gocyclo
    - gofmt
    - gosec
