project_name: cloud-mta-build-tool
before:
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: .
    ldflags: -s -w -X main.Version={{.Version}}  -X main.BuildDate={{.Date}}
    binary: mbt
    env:
      - GCO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
  format: tar.gz
  files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*
dist: dist
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
sign:
  cmd: gpg
  args:
    - --output
    - $signature
    - --detach-sig
    - $artifact
  signature: ${artifact}.sig
  artifacts: none


