project_name: cloud-mta-build-tool
before:
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
    main: .
    ldflags: -s -w -X main.Version={{.Version}}  -X main.BuildDate={{.Date}}
    binary: mbt
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
    format: tar.gz
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
      - src: 'micromatch/{{ .Os }}/*'
        dst: ./
        strip_parent: true
dist: dist
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
