#DIRS     := $(notdir $(shell find . -mindepth 1 -maxdepth 1 -type d))
#DIRNAMES := $(addprefix pdir-,$(DIRS))
#
#.PHONY: $(DIRNAMES)
#all: print-folder-names
#
#print-folder-names: $(DIRNAMES)
#
#pdir-tals: COMMAND := ' foo'
#
#$(DIRNAMES): pdir-%:
#	@printf '%s%s\n' '$*' $(COMMAND)

dir:
	@ls -d .

run:
	for dir in .; do echo $dir; done

