package main

import (
	"flag"
	"fmt"
	"io/ioutil"
)

func main() {
	// define commands for execution
	inFile := flag.String("source", "", "source")
	outFile := flag.String("target", "", "target")
	pkg := flag.String("package", "main", "Package name")
	name := flag.String("name", "File", "Identifier to use for the embedded data")
	flag.Parse()
	flag.Parse()
	//Read the config file
	inData, err := ioutil.ReadFile(*inFile)
	if err == nil {
		comment := "//This code generated by go generate command to include config file as binary, see generator file ; DO NOT EDIT!"
		template := "%s\npackage %s\n\nvar %s []byte = %#v\n"
		s := fmt.Sprintf(template, comment, *pkg, *name, inData)
		err = ioutil.WriteFile(*outFile, []byte(s), 0644)
	}
	if err != nil {
		panic(err.Error())
	}
}
