#!/usr/bin/env sh

# set readable variables
export JAVA_VERSION_TEMPLATE="$1"
export NODE_VERSION_TEMPLATE="$2"
export MBT_VERSION="$3"
export DOCKER_REGISTRY="$4"

# print parameters
echo "Java version: ${JAVA_VERSION_TEMPLATE}, Node version: ${NODE_VERSION_TEMPLATE}, \
MBT version: ${MBT_VERSION}, Docker Registry: ${DOCKER_REGISTRY}"

# common_image includes some exported vars and check methods
source $PWD/scripts/common_image

# publish image
echo "Publish mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION} to $DOCKER_REGISTRY"

docker tag mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION} ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION}
docker push ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION}
docker tag mbtci${JAVA_VERSION}${NODE_VERSION}:${MBT_VERSION} ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:latest
docker push ${DOCKER_REGISTRY}/mbtci${JAVA_VERSION}${NODE_VERSION}:latest
