site_name: Cloud MTA Build Tool
repo_url: https://github.com/SAP/cloud-mta-build-tool
nav:
  - Home: index.md
  - Usage: usage.md
  - Makefile: makefile.md
  - Roadmap: roadmap.md
  - Download And Installation: download.md

theme:
  name: 'material'
edit_uri: edit/master/docs/docs/

